{
	99={
		name="Luexks"
		playable=2
		primaries=3
		start="99_1"
		color0=0xff99ee
		color1=0xb6ccdb
		color2=0x0a0529
		explosionColor0=0x797cfd
        explosionColor1=0xff7efd
		thrustSFX=1
		aiflags=FLOCKING|RECKLESS|CAUTIOUS|SOCIAL|WANDER|HATES_PLANTS|FORGIVING|TRACTOR_TRANSIENT|DODGES|SMART_FIRE
	}
}
