{
	99={
		name="Luexks"
		playable=2
		primaries=3
		start="99_1"
		explosionColor0=0x797cfd
        explosionColor1=0xff7efd
		thrustSFX=1
		aiflags=FLOCKING|RECKLESS|CAUTIOUS|SOCIAL|WANDER|HATES_PLANTS|FORGIVING|TRACTOR_TRANSIENT|DODGES|SMART_FIRE